name: PyUp Security Scan

on:
  push: # Run on every push to any branch

jobs:
  safety:
    runs-on: ubuntu-latest
    steps:
      - uses: pyupio/safety@2.3.4
        with:
          api-key: ${{secrets.SAFETY_API_KEY}}
